services:
  mautic:
    image: mautic/mautic:${MAUTIC_VERSION:-5.2.8}
    container_name: mautic
    restart: unless-stopped
    environment:
      # Database configuration
      - MAUTIC_DB_HOST=db
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_NAME=${MAUTIC_DB_NAME:-mautic}
      - MAUTIC_DB_USER=${MAUTIC_DB_USER:-mautic}
      - MAUTIC_DB_PASSWORD=${MAUTIC_DB_PASSWORD}
      
      # Mautic configuration
      - MAUTIC_TRUSTED_HOSTS=${MAUTIC_TRUSTED_HOSTS}
      - MAUTIC_RUN_CRON_JOBS=true
      
      # PHP configuration
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-512M}
      - PHP_MAX_UPLOAD=${PHP_MAX_UPLOAD:-256M}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-300}
    volumes:
      # Persistent storage for Mautic data
      - mautic_data:/var/www/html
      
      # Plugins directory - mount this to easily add custom plugins
      - mautic_plugins:/var/www/html/plugins
      
      # Themes directory - optional for custom themes
      - mautic_themes:/var/www/html/themes
      
      # Media directory - for uploaded files and assets
      - mautic_media:/var/www/html/media
    # Ports are managed by Coolify proxy - uncomment for local development
    # ports:
    #   - "${MAUTIC_PORT:-8080}:80"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - mautic-network

  db:
    image: mariadb:${MARIADB_VERSION:-10.11}
    container_name: mautic-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MAUTIC_DB_NAME:-mautic}
      - MARIADB_USER=${MAUTIC_DB_USER:-mautic}
      - MARIADB_PASSWORD=${MAUTIC_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mautic-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mautic_data:
    name: mautic-app-data
    driver: local
  mautic_plugins:
    name: mautic-shared-plugins
    driver: local
    # SHARED VOLUME - Can be accessed by:
    # - mautic (this service)
    # - filebrowser (plugin manager - separate Coolify service)
  mautic_themes:
    name: mautic-shared-themes
    driver: local
    # SHARED VOLUME - Can be accessed by external services
  mautic_media:
    name: mautic-shared-media
    driver: local
    # SHARED VOLUME - Can be accessed by external services
  db_data:
    name: mautic-db-data
    driver: local

networks:
  mautic-network:
    name: mautic-network
    driver: bridge